// Code generated by protoc-gen-go.
// source: crypto/attributes/proto/attributes.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	crypto/attributes/proto/attributes.proto

It has these top-level messages:
	AttributesDataEntry
	AttributesData
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// AttributesDataEntry is an entry of AttributeData that store an attribute name with its respective key.
type AttributesDataEntry struct {
	AttributeName string `protobuf:"bytes,1,opt,name=AttributeName" json:"AttributeName,omitempty"`
	AttributeKey  []byte `protobuf:"bytes,2,opt,name=AttributeKey,proto3" json:"AttributeKey,omitempty"`
}

func (m *AttributesDataEntry) Reset()         { *m = AttributesDataEntry{} }
func (m *AttributesDataEntry) String() string { return proto.CompactTextString(m) }
func (*AttributesDataEntry) ProtoMessage()    {}

// AttributesData holds data required to access attributes (attributes names and keys).
type AttributesData struct {
	// Entries for each attributes considered.
	Entries []*AttributesDataEntry `protobuf:"bytes,2,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *AttributesData) Reset()         { *m = AttributesData{} }
func (m *AttributesData) String() string { return proto.CompactTextString(m) }
func (*AttributesData) ProtoMessage()    {}

func (m *AttributesData) GetEntries() []*AttributesDataEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}
